config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path("core/", include("src.core.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("src.users.urls")),
    path("houses/", include("src.houses.urls")),
    path("apartments/", include("src.apartments.urls")),
    path("statistic/", include("src.statistic.urls")),
    path("system/settings/", include("src.service.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apartments/urls.py
from django.urls import path

from .views import (
    CreateApartmentView,
    GetSectionsAndFloorsView,
    ApartmentsAjaxDatatableView,
    ApartmentsListView,
    DeleteApartmentView,
    ApartmentProfileView,
    EditApartmentView,
)

urlpatterns = [
    path("create/", CreateApartmentView.as_view(), name="apartment-create"),
    path(
        "get-sections-and-floors/",
        GetSectionsAndFloorsView.as_view(),
        name="get_sections_and_floors",
    ),
    path("", ApartmentsListView.as_view(), name="apartments"),
    path(
        "apartments/apartments/datatable/",
        ApartmentsAjaxDatatableView.as_view(),
        name="apartments-datatable",
    ),
    path(
        "<int:pk>/delete/",
        DeleteApartmentView.as_view(),
        name="apartment-delete",
    ),
    path(
        "apartment-profile/<int:apartment_id>/",
        ApartmentProfileView.as_view(),
        name="apartment-profile",
    ),
    path(
        "apartments/<int:pk>/edit/", EditApartmentView.as_view(), name="edit_apartment"
    ),
]

src/apartments/models.py
from django.db import models

from src.houses.models import Section, Floor, House
from src.service.models import Tariff
from src.users.models import User


class Apartment(models.Model):
    number = models.IntegerField()
    apartment_area = models.FloatField(default=0.0)
    house = models.ForeignKey(House, on_delete=models.CASCADE, blank=True, null=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, blank=True)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    tariff = models.ForeignKey(Tariff, on_delete=models.CASCADE, null=True, blank=True)


class ApartmentOwner(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"is_staff": False},
        null=True,
        blank=True,
        related_name="apartments",
    )
    apartment = models.ForeignKey(
        Apartment, on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return f"{self.user.name if self.user.name else self.user.email} - {self.apartment}"

src/apartments/forms/create_apartment_form.py
# from django import forms
# from src.houses.models import Section, Floor, Tariff, House
# from src.apartments.models import Apartment
# from django.contrib.auth import get_user_model
#
# User = get_user_model()
#
#
# class CreateApartmentForm(forms.ModelForm):
#     number = forms.CharField(
#         required=True,
#         label="Номер квартири",
#         widget=forms.TextInput(attrs={"class": "form-control"}),
#     )
#     apartment_area = forms.FloatField(
#         required=True,
#         label="Площа квартири",
#         widget=forms.TextInput(attrs={"class": "form-control"}),
#     )
#     house = forms.ModelChoiceField(
#         queryset=House.objects.all(),
#         required=True,
#         label="Дім",
#         widget=forms.Select(attrs={"class": "form-control select2"}),
#     )
#     section = forms.ModelChoiceField(
#         queryset=Section.objects.none(),  # Порожнє значення, поки дім не вибрано
#         required=True,
#         label="Секція",
#         widget=forms.Select(attrs={"class": "form-control select2"}),
#     )
#     floor = forms.ModelChoiceField(
#         queryset=Floor.objects.none(),  # Порожнє значення, поки дім не вибрано
#         required=True,
#         label="Поверх",
#         widget=forms.Select(attrs={"class": "form-control select2"}),
#     )
#     owner = forms.ModelChoiceField(
#         queryset=User.objects.filter(is_staff=False),
#         required=False,
#         label="Власник",
#         widget=forms.Select(attrs={"class": "form-control select2"}),
#     )
#     tariff = forms.ModelChoiceField(
#         queryset=Tariff.objects.all(),
#         required=False,
#         label="Тариф",
#         widget=forms.Select(attrs={"class": "form-control select2"}),
#     )
#
#     class Meta:
#         model = Apartment
#         fields = [
#             "number",
#             "apartment_area",
#             "house",
#             "section",
#             "floor",
#             "owner",
#             "tariff",
#         ]


from django import forms
from src.houses.models import Section, Floor, House
from src.service.models import Tariff
from src.apartments.models import Apartment
from django.contrib.auth import get_user_model

User = get_user_model()


class CreateApartmentForm(forms.ModelForm):
    number = forms.CharField(
        required=True,
        label="Номер квартири",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    apartment_area = forms.FloatField(
        required=True,
        label="Площа квартири",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    house = forms.ModelChoiceField(
        queryset=House.objects.all(),
        required=True,
        label="Дім",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )
    section = forms.ModelChoiceField(
        queryset=Section.objects.none(),  # Порожнє значення, поки дім не вибрано
        required=True,
        label="Секція",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )
    floor = forms.ModelChoiceField(
        queryset=Floor.objects.none(),  # Порожнє значення, поки дім не вибрано
        required=True,
        label="Поверх",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )
    owner = forms.ModelChoiceField(
        queryset=User.objects.filter(is_staff=False),
        required=False,
        label="Власник",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )
    tariff = forms.ModelChoiceField(
        queryset=Tariff.objects.all(),
        required=False,
        label="Тариф",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )

    class Meta:
        model = Apartment
        fields = [
            "number",
            "apartment_area",
            "house",
            "section",
            "floor",
            "owner",
            "tariff",
        ]

    # Оновлення queryset для полів section і floor
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        house_id = self.initial.get("house") or self.data.get("house")
        if house_id:
            self.fields["section"].queryset = Section.objects.filter(house_id=house_id)
            self.fields["floor"].queryset = Floor.objects.filter(house_id=house_id)

    # Валідація поля section
    def clean_section(self):
        section = self.cleaned_data.get("section")
        house = self.cleaned_data.get("house")
        if section and not Section.objects.filter(id=section.id, house=house).exists():
            raise forms.ValidationError(
                "Обрана секція не відповідає вибраному будинку."
            )
        return section

    # Валідація поля floor
    def clean_floor(self):
        floor = self.cleaned_data.get("floor")
        house = self.cleaned_data.get("house")
        if floor and not Floor.objects.filter(id=floor.id, house=house).exists():
            raise forms.ValidationError(
                "Обраний поверх не відповідає вибраному будинку."
            )
        return floor

src/apartments/views/apartment_profile_view.py
from django.views.generic import TemplateView

from src.apartments.models import Apartment


class ApartmentProfileView(TemplateView):
    template_name = "apartments/apartment_profile_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        apartment = Apartment.objects.get(id=self.kwargs["apartment_id"])
        context["apartment"] = apartment

        return context

src/apartments/views/apartments_database_view.py
from ajax_datatable import AjaxDatatableView
from django.urls import reverse
from django.views.generic import TemplateView

from src.apartments.models import Apartment
from src.houses.models import House
from src.users.models import User


# TODO: Додати відображення для Залишку як буде вже готова система обліку
class ApartmentsListView(TemplateView):
    template_name = "apartments/apartments_datatable.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["houses"] = House.objects.all()
        context["users"] = User.objects.all()
        return context


class ApartmentsAjaxDatatableView(AjaxDatatableView):
    model = Apartment
    title = "Квартири"
    initial_order = [["number", "asc"]]
    length_menu = [[10, 20, 50, 100, -1], [10, 20, 50, 100, "Всі"]]
    search_values_separator = "+"

    column_defs = [
        {
            "name": "id",
            "title": "ID",
            "visible": False,
            "orderable": True,
            "searchable": False,
        },
        {
            "name": "number",
            "title": "№ квартири",
            "visible": True,
            "orderable": True,
            "searchable": False,
        },
        {
            "name": "house__name",
            "title": "Дім",
            "visible": True,
            "orderable": False,
            "searchable": False,
            "foreign_field": "house__name",
        },
        {
            "name": "section__name",
            "title": "Секція",
            "visible": True,
            "orderable": False,
            "searchable": False,
            "foreign_field": "section__name",
        },
        {
            "name": "floor__number",
            "title": "Поверх",
            "visible": True,
            "orderable": False,
            "searchable": False,
            "foreign_field": "floor__number",
        },
        {
            "name": "owner",
            "title": "Власник",
            "visible": True,
            "orderable": False,
            "searchable": False,
        },
        {
            "name": "actions",
            "title": "Дії",
            "searchable": False,
            "orderable": True,
        },
    ]

    def get_initial_queryset(self, request=None):
        queryset = super().get_initial_queryset(request)
        house_id = self.request.GET.get("house_id")
        section_id = self.request.GET.get("section_id")
        floor_id = self.request.GET.get("floor_id")

        if house_id:
            queryset = queryset.filter(house_id=house_id)
        if section_id:
            queryset = queryset.filter(section_id=section_id)
        if floor_id:
            queryset = queryset.filter(floor_id=floor_id)

        return queryset

    def customize_row(self, row, obj):

        row["DT_RowAttr"] = {"data-id": obj.id}

        row["actions"] = """
            <div style="display: inline-flex; gap: 3px;">
                <a href="{}" class="btn btn-default btn-xs" title="Редагувати"><i class="fas fa-edit"></i></a>
                <button type="button" class="btn btn-default btn-xs delete-house-btn" title="Видалити" data-url="{}">
                    <i class="fas fa-trash"></i>
                </button>
            </div>
        """.format(
            reverse("edit_apartment", kwargs={"pk": obj.pk}),
            reverse("apartment-delete", kwargs={"pk": obj.pk}),
        )

src/apartments/views/create_apartment_view.py
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import FormView

from src.apartments.forms.create_apartment_form import CreateApartmentForm
from src.houses.models import Section, Floor


# TODO: Додати рахунок та тариф для зберігання
class CreateApartmentView(FormView):
    template_name = "apartments/create_apartment_page.html"
    form_class = CreateApartmentForm
    success_url = reverse_lazy("apartments")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    # Додано логіку для коректного оновлення queryset
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        house_id = self.request.POST.get("house")
        if house_id:
            kwargs["initial"] = kwargs.get("initial", {})
            kwargs["initial"]["house"] = house_id
        return kwargs

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class GetSectionsAndFloorsView(View):
    @staticmethod
    def get(request, *args, **kwargs):
        action = request.GET.get("action")
        house_id = request.GET.get("house_id")

        if action == "get_sections" and house_id:
            sections = Section.objects.filter(house_id=house_id).values("id", "name")
            return JsonResponse(list(sections), safe=False)

        if action == "get_floors" and house_id:
            floors = Floor.objects.filter(house_id=house_id).values("id", "number")
            return JsonResponse(list(floors), safe=False)

        return JsonResponse({"error": "Invalid action"}, status=400)

src/apartments/views/delete_apartment_view.py
from django.http import JsonResponse
from django.views import View
from src.apartments.models import Apartment


# view for delete an apartment
class DeleteApartmentView(View):
    def delete(self, request, *args, **kwargs):
        Apartment.objects.get(pk=self.kwargs["pk"]).delete()
        return JsonResponse(status=200, data={"success": True})

src/apartments/views/edit_apartment_view.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from src.apartments.forms.create_apartment_form import CreateApartmentForm
from src.apartments.models import Apartment


class EditApartmentView(FormView):
    template_name = "apartments/edit_apartment_page.html"
    form_class = CreateApartmentForm
    success_url = reverse_lazy("apartments")

    def get_object(self):
        # Завантажуємо об'єкт на основі `pk` з URL
        pk = self.kwargs.get("pk")
        return get_object_or_404(Apartment, pk=pk)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Додаємо об'єкт як instance у форму
        kwargs["instance"] = self.get_object()
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["apartment"] = (
            self.get_object()
        )  # Передаємо об'єкт в контекст для шаблону
        return context

    def form_valid(self, form):
        # Зберігаємо зміни в об'єкті
        form.save()
        return redirect(self.success_url)

    def form_invalid(self, form):
        # У разі помилки повертаємо форму з помилками
        return self.render_to_response(self.get_context_data(form=form))

src/apartments/templates/apartments/create_apartment_page.html
{% extends "admin/adminlte_base.html" %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'apartments' %}">Квартири</a>
        </li>
        <li class="breadcrumb-item active">Нова квартира</li>
    </ol>
{% endblock breadcrumb %}
{% block page_title %}
    Нова квартира
{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="uk">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="CRM Admin Panel">
        <meta name="keywords" content="admin panel, crm">
        <title>Створити квартиру</title>
        {{ form.media }}
        <style>
        .form-group.has-error .form-control,
        .form-group.has-error .input-group-addon {
            border-color: #dd4b39;
            box-shadow: none;
        }
        .form-group.has-success .form-control,
        .form-group.has-success .input-group-addon {
            border-color: #00a65a;
            box-shadow: none;
        }
        .select2-container {
            display: none !important;
        }
        </style>
    </head>
    <body class="hold-transition sidebar-mini">
        <div class="wrapper">
            <!-- Content Wrapper -->
            <div class="content-wrapper">
                {% block content %}
                    <div class="card card-default">
                        <div class="card-body">
                            <form method="post"
                                  enctype="multipart/form-data"
                                  action="{% url 'apartment-create' %}">
                                {% csrf_token %}
                                <!-- Apartment Form -->
                                <div class="row">
                                    <div class="col-md-6">
                                        <!-- Номер квартири -->
                                        <div class="form-group">
                                            {{ form.number.label_tag }}
                                            {{ form.number }}
                                        </div>
                                        <!-- Площа квартири -->
                                        <div class="form-group">
                                            {{ form.apartment_area.label_tag }}
                                            {{ form.apartment_area }}
                                        </div>
                                        <!-- Будинок -->
                                        <div class="form-group">
                                            {{ form.house.label_tag }}
                                            {{ form.house }}
                                        </div>
                                        <!-- Секція -->
                                        <div class="form-group">
                                            {{ form.section.label_tag }}
                                            {{ form.section }}
                                        </div>
                                        <!-- Поверх -->
                                        <div class="form-group">
                                            {{ form.floor.label_tag }}
                                            {{ form.floor }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <!-- Власник -->
                                        <div class="form-group">
                                            {{ form.owner.label_tag }}
                                            {{ form.owner }}
                                        </div>
                                        <!-- Тариф -->
                                        <div class="form-group">
                                            {{ form.tariff.label_tag }}
                                            {{ form.tariff }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-12 d-flex justify-content-end">
                                        <a href="{% url 'houses' %}" class="btn btn-secondary mr-2">Відмінити</a>
                                        <button type="submit" class="btn btn-success">Зберегти</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endblock content %}
            </div>
        </div>
        {% block extra_js %}
            <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
            <script src="{% static 'adminlte/plugins/select2/js/select2.full.min.js' %}"></script>
            <script>
    $(document).ready(function () {
        $('.select2').select2({
            theme: 'bootstrap4',
            width: '100%',
            allowClear: true
        });
        $('.select2-hidden-accessible').removeAttr('aria-hidden tabindex');
        $('.select2-container').hide(); // Hide the Select2 container
        $('#id_house').on('change', function () {
    const houseId = $(this).val();
    // Очищення полів section і floor
    $('#id_section').val(null).trigger('change');
    $('#id_floor').val(null).trigger('change');
        // AJAX для оновлення секцій та поверхів
        $('#id_house').on('change', function () {
            const houseId = $(this).val();
            $.ajax({
                url: '{% url "get_sections_and_floors" %}',
                data: {
                    action: "get_sections",
                    house_id: houseId,
                },
                success: function (data) {
                    $('#id_section').empty().append('<option value="">Оберіть секцію</option>');
                    $.each(data, function (index, section) {
                        $('#id_section').append(
                            `<option value="${section.id}">${section.name}</option>`
                        );
                    });
                },
            });

            $.ajax({
                url: '{% url "get_sections_and_floors" %}',
                data: {
                    action: "get_floors",
                    house_id: houseId,
                },
                success: function (data) {
                    $('#id_floor').empty().append('<option value="">Оберіть поверх</option>');
                    $.each(data, function (index, floor) {
                        $('#id_floor').append(
                            `<option value="${floor.id}">${floor.number}</option>`
                        );
                    });
                },
            });
        });
    });
        });
            </script>
        {% endblock extra_js %}
    </body>
</html>

src/apartments/templates/apartments/edit_apartment_page.html
{% extends "admin/adminlte_base.html" %}
{% block breadcrumb %}
    <ol class="breadcrumb">

        <li class="breadcrumb-item active"><a href="{% url 'apartment-profile' apartment.id %}">Квартира
            №{{ apartment.number }}, {{ apartment.house.name }}</a></li>
        <li class="breadcrumb-item active">Редагування</li>
    </ol>
{% endblock breadcrumb %}
{% block page_title %}
    Редагування квартири №{{ apartment.number }},  {{ apartment.house.name }}
{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="CRM Admin Panel">
    <meta name="keywords" content="admin panel, crm">
    <title>Редагувати квартиру</title>
    {{ form.media }}
    <style>
        .form-group.has-error .form-control,
        .form-group.has-error .input-group-addon {
            border-color: #dd4b39;
            box-shadow: none;
        }

        .form-group.has-success .form-control,
        .form-group.has-success .input-group-addon {
            border-color: #00a65a;
            box-shadow: none;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
    <!-- Content Wrapper -->
    <div class="content-wrapper">
        {% block content %}
            <div class="card card-default">
                <div class="card-body">
                    <form method="post"
                          enctype="multipart/form-data"
                          action="{% url 'edit_apartment' apartment.pk %}">
                        {% csrf_token %}
                        <!-- Apartment Form -->
                        <div class="row">
                            <div class="col-md-6">
                                <!-- Номер квартири -->
                                <div class="form-group">
                                    {{ form.number.label_tag }}
                                    {{ form.number }}
                                </div>
                                <!-- Площа квартири -->
                                <div class="form-group">
                                    {{ form.apartment_area.label_tag }}
                                    {{ form.apartment_area }}
                                </div>
                                <!-- Будинок -->
                                <div class="form-group">
                                    {{ form.house.label_tag }}
                                    {{ form.house }}
                                </div>
                                <!-- Секція -->
                                <div class="form-group">
                                    {{ form.section.label_tag }}
                                    {{ form.section }}
                                </div>
                                <!-- Поверх -->
                                <div class="form-group">
                                    {{ form.floor.label_tag }}
                                    {{ form.floor }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <!-- Власник -->
                                <div class="form-group">
                                    {{ form.owner.label_tag }}
                                    {{ form.owner }}
                                </div>
                                <!-- Тариф -->
                                <div class="form-group">
                                    {{ form.tariff.label_tag }}
                                    {{ form.tariff }}
                                </div>
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col-12 d-flex justify-content-end">
                                <a href="{% url 'apartments' %}" class="btn btn-secondary mr-2">Відмінити</a>
                                <button type="submit" class="btn btn-success">Зберегти</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock content %}
    </div>
</div>
{% block extra_js %}
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/select2/js/select2.full.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.select2').select2({
                theme: 'bootstrap4',
                width: '100%',
                allowClear: true
            });
            $('.select2-hidden-accessible').removeAttr('aria-hidden tabindex');
            $('.select2-container').hide(); // Hide the Select2 container
            $('#id_house').on('change', function () {
                const houseId = $(this).val();

                $('#id_section').val(null).trigger('change');
                $('#id_floor').val(null).trigger('change');

                $('#id_house').on('change', function () {
                    const houseId = $(this).val();
                    $.ajax({
                        url: '{% url "get_sections_and_floors" %}',
                        data: {
                            action: "get_sections",
                            house_id: houseId,
                        },
                        success: function (data) {
                            $('#id_section').empty().append('<option value="">Оберіть секцію</option>');
                            $.each(data, function (index, section) {
                                $('#id_section').append(
                                    `<option value="${section.id}">${section.name}</option>`
                                );
                            });
                        },
                    });

                    $.ajax({
                        url: '{% url "get_sections_and_floors" %}',
                        data: {
                            action: "get_floors",
                            house_id: houseId,
                        },
                        success: function (data) {
                            $('#id_floor').empty().append('<option value="">Оберіть поверх</option>');
                            $.each(data, function (index, floor) {
                                $('#id_floor').append(
                                    `<option value="${floor.id}">${floor.number}</option>`
                                );
                            });
                        },
                    });
                });
            });
        });
    </script>
{% endblock extra_js %}
</body>
</html>